services:
  circus:
    build: .
    container_name: circus-dev
    volumes:
      - .:/app
    environment:
      - ANDROID_ADB_SERVER_HOST=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    working_dir: /app
