name: warm_like_posts
description: Scroll Instagram feed and like posts intermittently to build engagement signals
target_package: com.instagram.android
timeout: 300.0
retry_count: 0
actions:
- action: app_start
  package: com.instagram.android
- action: random_sleep
  min: 2
  max: 4
# Dismiss popups
- action: if
  condition:
    element_exists:
      text: Not Now
  then:
  - action: tap
    text: Not Now
  - action: random_sleep
    min: 1
    max: 2
# Scroll and like pattern: scroll 2-3 times, then like if button visible
- action: try
  actions:
  - action: repeat
    count: 6
    actions:
    # Scroll a few times
    - action: swipe
      direction: up
    - action: random_sleep
      min: 2
      max: 4
    - action: swipe
      direction: up
    - action: random_sleep
      min: 2
      max: 5
    # Try to like a post if like button is visible
    - action: if
      condition:
        element_exists:
          resource_id: com.instagram.android:id/row_feed_button_like
      then:
      - action: tap
        resource_id: com.instagram.android:id/row_feed_button_like
      - action: random_sleep
        min: 1
        max: 3
    - action: swipe
      direction: up
    - action: random_sleep
      min: 2
      max: 4
  on_error:
  - action: screenshot
- action: screenshot
